version: "2.0"
services:
  omada:
    build: https://github.com/qdm12/omada.git
    image: qdm12/omada
    container_name: omada
    ports:
      - 8043:8043/tcp
      - 27001:27001/udp
      - 27002:27002/tcp
      - 29810:29810/udp
      - 29811:29811/tcp
      - 29812:29812/tcp
      - 29813:29813/tcp
    environment:
      - HTTPPORT=8088
      - HTTPSPORT=8043
    volumes:
      - /var/log/omada:/omada/logs
      - /var/omada/data:/omada/data
    restart: unless-stopped
